FROM php:8.4-fpm

# UID/GID хостового пользователя прокинем из docker-compose
ARG UID=1000
ARG GID=1000

RUN apt-get update \
    && apt-get install -y zlib1g-dev g++ git libicu-dev zip libzip-dev zip libpq-dev libpng-dev libwebp-dev libxpm-dev \
    && docker-php-ext-install intl opcache pdo pgsql pdo_mysql pdo_pgsql gd \
    && pecl install apcu \
    && docker-php-ext-enable apcu \
    && docker-php-ext-configure zip \
    && docker-php-ext-install zip \
    && pecl install xdebug \
    && docker-php-ext-enable xdebug

RUN groupmod -g "${GID}" www-data \
 && usermod -u "${UID}" -g "${GID}" www-data

WORKDIR /var/www/rns_telcom

COPY ./conf/local-dev.ini /usr/local/etc/php/conf.d/local-dev.ini

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
RUN curl -sS https://get.symfony.com/cli/installer | bash

#RUN usermod -u $UID www-data -s /bin/bash && groupmod -g $GID www-data
#RUN chown -R www-data:www-data /var/www/rns_telcom
#COPY ./conf/local-dev.ini /usr/local/etc/php/php.ini
USER www-data
