<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260124192503 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE calculations (
    id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id INT NOT NULL,
    name VARCHAR(255) NOT NULL,
    type VARCHAR(50) NOT NULL,
    status VARCHAR(20) NOT NULL,
    created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
    deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
    PRIMARY KEY (id))');

        $this->addSql('CREATE INDEX IDX_4BFD195EA76ED395 ON calculations (user_id)');

        $this->addSql('ALTER TABLE calculations ADD CONSTRAINT FK_4BFD195EA76ED395 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE');


        $this->addSql('CREATE TABLE calculation_data (
    id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    calculation_id INT NOT NULL,
    object_code VARCHAR(50) DEFAULT NULL,
    base_station_number VARCHAR(50) DEFAULT NULL,
    region VARCHAR(100) DEFAULT NULL,
    locality VARCHAR(100) DEFAULT NULL,
    customer VARCHAR(150) DEFAULT NULL,
    ams_type VARCHAR(100) DEFAULT NULL,
    ams_height NUMERIC(6, 2) DEFAULT NULL,
    survey_date DATE DEFAULT NULL,
    wind_region VARCHAR(10) DEFAULT NULL,
    terrain_type VARCHAR(5) DEFAULT NULL,
    snow_region VARCHAR(10) DEFAULT NULL,
    icing_region VARCHAR(10) DEFAULT NULL,
    latitude NUMERIC(10, 7) DEFAULT NULL,
    longitude NUMERIC(10, 7) DEFAULT NULL,
    specific_data JSON DEFAULT NULL,
    created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
    PRIMARY KEY (id))');

        $this->addSql('CREATE UNIQUE INDEX UNIQ_D1FBD6E0CE3D4B33 ON calculation_data (calculation_id)');
        $this->addSql('ALTER TABLE calculation_data ADD CONSTRAINT FK_D1FBD6E0CE3D4B33 FOREIGN KEY (calculation_id) REFERENCES calculations (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE calculation_data DROP CONSTRAINT FK_D1FBD6E0CE3D4B33');
        $this->addSql('ALTER TABLE calculations DROP CONSTRAINT FK_4BFD195EA76ED395');
        $this->addSql('DROP TABLE calculation_data');
        $this->addSql('DROP TABLE calculations');
    }
}
