<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260202131137 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE equipment (
    id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    brand VARCHAR(255) NOT NULL,
    model VARCHAR(255) NOT NULL,
    full_name VARCHAR(512) NOT NULL,
    type VARCHAR(50) NOT NULL,
    has_diameter BOOLEAN NOT NULL,
    diameter NUMERIC(8, 2) DEFAULT NULL,
    height NUMERIC(8, 2) DEFAULT NULL,
    width NUMERIC(8, 2) DEFAULT NULL,
    depth NUMERIC(8, 2) DEFAULT NULL,
    weight NUMERIC(8, 2) DEFAULT NULL,
    created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
    PRIMARY KEY (id))');
        $this->addSql("CREATE INDEX idx_equipment_fulltext ON equipment USING GIN (to_tsvector('english', full_name))");
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE equipment');
    }
}
